title = "BS CV"
baseURL = "https://bobsponge.netlify.app/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = ""
email = "bs@morebs.io"
favicon = "/favicon.ico"
firstName = "Bob"
lastName = "Sponge"
phone = ""
profileImage = "img/bob.png"
showEducation = true
showExperience = true
showOpenSource = true
showProjects = true
showPublications = true
showQr = true
showSkills = true

[params.google]

[params.google.analytics]
trackerID = ""

[[params.handles]]
link = "https://www.linkedin.com/in/sponge-b-2738611ba"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/spongebob-squarepants-815b041a/"
name = "GitHub"

[[params.handles]]
link = "https://mobile.twitter.com/SpongeBob"
name = "Twitter"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
